'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '@/lib/supabase/client';
import { Button } from '@/components/ui/Button';
import { Input, Label } from '@/components/ui/Input';
import { Disclaimer } from '@/components/Disclaimer';

export default function SignupPage() {
  const router = useRouter();
    const [nome, setNome] = useState('');
      const [email, setEmail] = useState('');
        const [senha, setSenha] = useState('');
          const [loading, setLoading] = useState(false);
            const [erro, setErro] = useState<string | null>(null);

              async function handleSubmit(e: React.FormEvent) {
                  e.preventDefault();
                      setLoading(true);
                          setErro(null);
                              try {
                                    const supabase = createClient();
                                          const { error } = await supabase.auth.signUp({
                                                  email,
                                                          password: senha,
                                                                  options: {
                                                                            data: { nome },
                                                                                      emailRedirectTo: `${window.location.origin}/auth/callback?next=/onboarding`,
                                                                                              },
                                                                                                    });
                                                                                                          if (error) throw error;
                                                                                                                router.push('/onboarding');
                                                                                                                    } catch (e: any) {
                                                                                                                          setErro(e.message || 'Erro ao criar conta.');
                                                                                                                              } finally {
                                                                                                                                    setLoading(false);
                                                                                                                                        }
                                                                                                                                          }

                                                                                                                                            async function signInWithGoogle() {
                                                                                                                                                const supabase = createClient();
                                                                                                                                                    await supabase.auth.signInWithOAuth({
                                                                                                                                                          provider: 'google',
                                                                                                                                                                options: { redirectTo: `${window.location.origin}/auth/callback` },
                                                                                                                                                                    });
                                                                                                                                                                      }

                                                                                                                                                                        return (
                                                                                                                                                                            <>
                                                                                                                                                                                  <div className="min-h-screen flex items-center justify-center p-4 bg-gradient-to-br from-ink-100 to-white">
                                                                                                                                                                                          <div className="w-full max-w-md">
                                                                                                                                                                                                    <Link href="/" className="display text-3xl text-center block mb-8">
                                                                                                                                                                                                                <span className="text-brand-green">Troca</span>
                                                                                                                                                                                                                            <span className="text-ink-900">Copa</span>
                                                                                                                                                                                                                                      </Link>

                                                                                                                                                                                                                                                <div className="bg-white rounded-2xl shadow-lg p-8 border border-ink-100">
                                                                                                                                                                                                                                                            <h1 className="display text-2xl mb-2">Criar conta gratis</h1>
                                                                                                                                                                                                                                                                        <p className="text-sm text-gray-600 mb-6">
                                                                                                                                                                                                                                                                                      Comece a trocar hoje. Cadastro em 30 segundos.
                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                                                                            onClick={signInWithGoogle}
                                                                                                                                                                                                                                                                                                                                          className="w-full mb-4 flex items-center justify-center gap-3 border-2 border-ink-100 rounded-xl px-4 py-2.5 hover:bg-ink-100 transition-colors"
                                                                                                                                                                                                                                                                                                                                                        type="button"
                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                  <svg className="h-5 w-5" viewBox="0 0 24 24">
                                                                                                                                                                                                                                                                                                                                                                                                  <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                                                                                                                                                                                                                                                                                                                                                                                                                  <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                                                                                                                                                                                                                                                                                                                                                                                                                                  <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="font-medium">Continuar com Google</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="my-4 flex items-center gap-3 text-xs text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex-1 h-px bg-ink-100"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ou com e-mail
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex-1 h-px bg-ink-100"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <form onSubmit={handleSubmit} className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Label htmlFor="nome">Nome</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Input id="nome" required value={nome} onChange={(e) => setNome(e.target.value)} placeholder="Como gosta de ser chamado" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Label htmlFor="email">E-mail</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Input id="email" type="email" required value={email} onChange={(e) => setEmail(e.target.value)} placeholder="seu@email.com" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Label htmlFor="senha">Senha</Label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Input id="senha" type="password" required minLength={6} value={senha} onChange={(e) => setSenha(e.target.value)} placeholder="Minimo 6 caracteres" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {erro && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-sm text-red-600 bg-red-50 rounded-lg px-3 py-2">{erro}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button type="submit" variant="primary" className="w-full" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? 'Criando conta...' : 'Criar conta'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-sm text-center text-gray-500 mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Ja tem conta?{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link href="/login" className="text-brand-green font-medium hover:underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Entrar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Disclaimer />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }