'use client';
import { useState, useEffect, useCallback } from 'react';

interface PixData {
  payment_id: number;
    qr_code: string;
      qr_code_base64: string;
        expires_at: string;
        }
        
        interface Props {
          onClose: () => void;
            onPaid: () => void;
            }
            
            export default function PixModal({ onClose, onPaid }: Props) {
              const [loading, setLoading] = useState(true);
                const [pix, setPix] = useState<PixData | null>(null);
                  const [error, setError] = useState('');
                    const [copied, setCopied] = useState(false);
                      const [polling, setPolling] = useState(false);
                      
                        useEffect(() => {
                            fetch('/api/pagamentos/checkout-pix', { method: 'POST' })
                                  .then(r => r.json())
                                        .then(d => {
                                                if (d.error) throw new Error(d.error);
                                                        setPix(d);
                                                                setPolling(true);
                                                                      })
                                                                            .catch(e => setError(e.message))
                                                                                  .finally(() => setLoading(false));
                                                                                    }, []);
                                                                                    
                                                                                      const checkStatus = useCallback(async () => {
                                                                                          if (!pix) return;
                                                                                              const url = '/api/pagamentos/status?payment_id=' + pix.payment_id;
                                                                                                  const r = await fetch(url).then(x => x.json()).catch(() => ({}));
                                                                                                      if (r.status === 'approved') {
                                                                                                            setPolling(false);
                                                                                                                  onPaid();
                                                                                                                      }
                                                                                                                        }, [pix, onPaid]);
                                                                                                                        
                                                                                                                          useEffect(() => {
                                                                                                                              if (!polling) return;
                                                                                                                                  const t = setInterval(checkStatus, 5000);
                                                                                                                                      return () => clearInterval(t);
                                                                                                                                        }, [polling, checkStatus]);
                                                                                                                                        
                                                                                                                                          function handleBackdrop(e: React.MouseEvent<HTMLDivElement>) {
                                                                                                                                              if (e.target === e.currentTarget) onClose();
                                                                                                                                                }
                                                                                                                                                
                                                                                                                                                  function copiar() {
                                                                                                                                                      if (!pix?.qr_code) return;
                                                                                                                                                          navigator.clipboard.writeText(pix.qr_code);
                                                                                                                                                              setCopied(true);
                                                                                                                                                                  setTimeout(() => setCopied(false), 3000);
                                                                                                                                                                    }
                                                                                                                                                                    
                                                                                                                                                                      return (
                                                                                                                                                                          <div
                                                                                                                                                                                className="fixed inset-0 bg-black/60 flex items-center justify-center z-50 p-4"
                                                                                                                                                                                      onClick={handleBackdrop}
                                                                                                                                                                                          >
                                                                                                                                                                                                <div className="bg-white rounded-2xl max-w-sm w-full p-6 shadow-xl">
                                                                                                                                                                                                        <div className="flex items-center justify-between mb-4">
                                                                                                                                                                                                                  <h2 className="font-bold text-lg">Pagar com Pix</h2>
                                                                                                                                                                                                                            <button onClick={onClose} className="text-gray-400 hover:text-gray-600 text-2xl leading-none">
                                                                                                                                                                                                                                        &times;
                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                  <p className="text-sm text-gray-500 mb-4 text-center">
                                                                                                                                                                                                                                                                            R$29,90 — Premium ativo por 30 dias. QR expira em 30 min.
                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                            {loading && (
                                                                                                                                                                                                                                                                                                      <div className="flex flex-col items-center py-8 gap-3">
                                                                                                                                                                                                                                                                                                                  <div className="w-8 h-8 border-4 border-green-500 border-t-transparent rounded-full animate-spin" />
                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-gray-400">Gerando QR Code...</p>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                        {error && (
                                                                                                                                                                                                                                                                                                                                                                  <div className="text-center py-4">
                                                                                                                                                                                                                                                                                                                                                                              <p className="text-red-500 text-sm">{error}</p>
                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={onClose} className="mt-2 text-sm underline text-red-400">
                                                                                                                                                                                                                                                                                                                                                                                                        Fechar
                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                              {pix && !loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex flex-col items-center gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {pix.qr_code_base64 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="border-4 border-green-500 rounded-xl p-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    src={'data:image/png;base64,' + pix.qr_code_base64}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alt="QR Pix"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-48 h-48"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="w-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs text-gray-400 mb-1 text-center">Pix copia e cola:</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            readOnly
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={pix.qr_code}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex-1 text-xs border rounded-lg px-2 py-2 bg-gray-50 truncate"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onClick={copiar}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="px-3 py-2 bg-green-500 text-white text-xs rounded-lg hover:bg-green-600"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {copied ? 'Copiado!' : 'Copiar'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center gap-2 text-sm text-gray-400">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="w-2 h-2 bg-green-400 rounded-full animate-pulse" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span>Aguardando pagamento...</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-xs text-gray-400 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Premium ativado automaticamente apos o pagamento.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }'